### ISSUE TITLE
handshake has wrong thread count argument order

### ISSUE THREAD

**Issue by quarckster** [openssl/perftools#10]
If thread count argument is placed in the end of the command the benchmark fails with the error:

```
LD_LIBRARY_PATH=${HOME}/openssl-3.0-test ./handshake -t -s ${HOME}/test 10
threadcount must be > 0
```

Expected result: thread count argument must be accepted in the end of the command

**Comment by quarckster** [comment]
This issue is also can be reproduced for `x509storeissuer`

**Comment by Sashan** [comment]
speaking of `handshake` test. The '-s` option sets `share_ctx` flag. It does not expect any value. (`${HOME}/test}`).
the test is supposed to be run with command line
```
./handshake -t -s 10
```

**Comment by Sashan** [comment]
there is no '-s' option at `x509storeissue`. and my earlier comments on handshake command line  was wrong.
the command line looks as:
```
./handshake -t 10 -s 10 path/to/openssl-sources/test/certs
```
and same goes to `x509storeissuer`
```
./x509storeissuer -t 10 path/to/openssl-sources/test/certs
```
